### PR TITLE
Feature/changesets

### PR DESCRIPTION
**Pull request by no-reply**
This makes changes relevant for [#250](https://github.com/ruby-rdf/rdf/pull/250).

### CODE REVIEW

**Comment by no-reply** [comment]
This depends on https://github.com/ruby-rdf/rdf/pull/250. One of the two will need to be merged before the other for CI to pass.

**Comment by gkellogg** [comment]
I think that removing Enumerable from Queryable is something that should happen to 2.0, if at all, as it's a breaking change. If we leave it to 2.1, we'd be breaking semantic versioning.

Most uses of Queryable methods (e.g., `#first`) probably use a pattern, when they don't then some enumerator is necessary. Note that **first** isn't very useful unless the solutions are ordered; it's really more like **sample**.

`Queryable#enum_for` leverages `Enumerable#enum_for` for enumerating solutions.

OTOH, for people to be able to use a Transaction consistently, it probably has to be Enumerable. We should probably go with your second solution and implement `#each`. If this proves to be a performance issue, we can address at a later date.

**Comment by gkellogg** [comment]
Otherwise, I think this is probably good to go.

**Comment by no-reply** [comment]
> OTOH, for people to be able to use a Transaction consistently, it probably has to be Enumerable. We should probably go with your second solution and implement #each. If this proves to be a performance issue, we can address at a later date.

:+1:. If Transactions become `Enumerable`, is there any reason they shouldn't also be `Readable`? I suppose I could try adding the mixin and running the tests; but if you can warn me off a yak shave, that would be great.

**Pull request merged**
