### PR TITLE
Add tests for transaction graph names

### PR DESCRIPTION
**Pull request by no-reply**
The reference implementation of `RDF::Transaction` destroys graph names
on statements passed in. This tests the handling of graph names in
preparation for a patch.

### CODE REVIEW

**Comment by gkellogg** [comment]
LGTM, but might not survive @bendiken's rewrite. Let's give him a bit of time for comment before pulling.

**Comment by no-reply** [comment]
Good idea. We should make sure something that passes these tests makes its way into `Changeset` one way or another.

**Comment by no-reply** [comment]
Since https://github.com/ruby-rdf/rdf/pull/222 got merged, do we want to get this in?

**Comment by gkellogg** [comment]
Fine with me, but it will need to go into 1.99.1; @bendiken may have an opinion.

**Comment by bendiken** [comment]
I think this can be merged, because it's for the 1.x series, not 2.x. For 2.0, I will forward-port this to `RDF::Changeset`; and in 2.0, `RDF::Transaction` does not have a graph name any longer.

**Pull request merged**
